module.exports = {
  ron: [
    'Clear alcohols are for rich women on diets.',
    'Crying: acceptable at funerals and the Grand Canyon.',
    'I call this turf \'n turf. It\'s a 16 oz T-bone and a 24 oz porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.',
    'Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.',
    'I\'m a simple man. I like pretty, dark-haired women, and breakfast food.',
    'Never half-ass two things. Whole-ass one thing.',
    '[On bowling] Straight down the middle. No hook, no spin, no fuss. Anything more and this becomes figure skating.',
    'I don\'t want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief.',
    'Fishing relaxes me. It\'s like yoga, except I still get to kill something.',
    'No home is complete without a proper toolbox. Here\'s April and Andy\'s: A hammer, a half eaten pretzel, a baseball card, some cartridge that says Sonic and Hedgehog, a scissor half, a flashlight filled with jellybeans.',
    'Just give me all the bacon and eggs you have. Wait...wait. I worry what you just heard was: Give me a lot of bacon and eggs. What I said was: Give me all the bacon and eggs you have. Do you understand?',
    'When people get a little too chummy with me I like to call them by the wrong name to let them know I don\'t really care about them.',
    'There\'s only one thing I hate more than lying: skim milk. Which is water that\'s lying about being milk.',
    'The government is a greedy piglet that suckles on a taxpayer\'s teat until they have sore, chapped nipples.',
    'The less I know about other people\'s affairs, the happier I am. I\'m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.',
    'When I eat, it is the food that is scared.',
    'My only official recommendations are US Army-issued mustache trimmers, Morton\'s Salt, and the C.R. Lawrence Fein two inch axe-style scraper oscillating knife blade.',
    'Are you going to tell a man that he can\'t fart in his own car?',
    'Turkey can never beat cow.',
    'It\'s always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.',
    'There are three acceptable haircuts: high and tight, crew cut, buzz cut.',
    'Capitalism: God\'s way of determining who is smart and who is poor.',
    'Any dog under fifty pounds is a cat and cats are useless.',
    'Fish, for sport only, not for meat. Fish meat is practically a vegetable.',
    'There is only one bad word: taxes.',
    'History began July 4th, 1776. Anything before that was a mistake.',
    'Cultivating a manly musk puts opponent on notice.',
    'Give a man a fish and feed him for a day. Don\'t teach a man to fish… and feed yourself. He\'s a grown man. And fishing\'s not that hard.',
    'Child labor laws are ruining this country.',
    'Great job, everyone. The reception will be held in each of our individual houses, alone.',
    'America: The only country that matters. If you want to experience other \'cultures,\' use an atlas or a ham radio.',
    'The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.',
    'There are only three ways to motivate people: money, fear, and hunger.',
    'Shorts over six inches are capri pants, shorts under six inches are European.',
    'Friends: one to three is sufficient.',
    'Breakfast food can serve many purposes.',
    'Honor: if you need it defined, you don\'t have it.',
    'One rage every three months is permitted. Try not to hurt anyone who doesn\'t deserve it.',
    'Strippers do nothing for me…but I will take a free breakfast buffet anytime, anyplace.',
    'I like saying \'No,\' it lowers their enthusiasm.',
    'You had me at meat tornado.',
    'There must be a mistake, you\'ve accidentally given me the food that my food eats.',
    'Son, there is no wrong way to consume alcohol.',
    'Keep your tears in your eyes where they belong.',
    'I\'ve cried twice in my life. Once when I was seven and hit by a school bus. And then again when I heard that Li\'l Sebastian has passed.',
    'I hate everything.',
    'I love nothing.',
    'I love riddles!',
    'Don\'t waste energy moving unless necessary.',
    'I\'ll take that steak to go. Please and thank you.',
    'Creativity is for people with glasses who like to lie.',
    'Children are terrible artists and artists are crooks.',
    'Tom put all my records into this rectangle!',
    'I believe luck is a concept invented by the weak to explain their failures.',
    'What\'s cholesterol?',
    'People who buy things are suckers.',
    'I\'m going to get 12 eggs and part of a dead animal. Dealer\'s choice. Please and thank you.',
    'What the fuck is a German muffin?!?',
    'I wanna punch you in the face so bad right now.'
  ],
  leslie: [
    'We have to remember what\'s important in life: friends, waffles, and work. Or waffles, friends, work. But work has to come third.',
    'Hoes before bros. Uteruses before duderuses. Ovaries before brovaries.',
    'I stand behind my decision to avoid salad and other disgusting things.',
    'I\'m a goddess, a glorious female warrior.',
    'Guys love it when you can show them you\'re better than they are at something they love.',
    'Ann, you are a beautiful, talented, brilliant, powerful musk ox.',
    'What I hear when I\'m being yelled at is people caring loudly at me.',
    'Some people object to powerful depictions of awesome ladies.',
    'Sophisticated with a hint of slutty.',
    'One person\'s \'annoying\' is another person\'s \'inspiring and heroic\'.',
    'I am big enough to admit that I am often inspired by myself.',
    'Why would anyone ever eat anything besides breakfast food?',
    'If I had to have a stripper’s name it would be Equality.'
  ],
  tom: [
    'Your favorite kind of cake can\'t be birthday cake, that\'s like saying your favorite kind of cereal is breakfast cereal.',
    'Whenever Leslie asks me for the Latin names of any of our plants, I just give her the names of rappers. Those are some Diddies. Those are some Bone Thugs-N-Harmoniums, right here. Those Ludacrises are coming in great.',
    'At the risk bragging, one of the things I\'m best at is riding coattails. Behind every successful man is me, smiling and taking partial credit.',
    'I want to take that cheese and do terrible things to it.',
    'The four sweetest words in the English language — \'You wore me down.\'',
    'I want to open up my own club one day, maybe call it something like Club a Dub Dub, or the Club Marine. Sort of a submarine-themed club. Or Tom\'s Bistro. The word \'bistro\' is classy as shit.',
    'No, I don\'t text her, \'It was nice meeting you.\' I wait eight weeks and I text her, \'What\'s crackin?\'',
    '\'Zerts\' are what I call desserts. \'Tree-trees\' are entrees. I call sandwiches \'sammies,\' \'sandoozles,\' or \'Adam Sandlers.\' Air conditioners are \'cool blasterz\' with a \'z\' — I don\'t know where that came from. I call cakes \'big ol\' cookies.\' I call noodles \'long-ass rice.\' Fried chicken is \'fry-fry chicky-chick.\' Chicken parm is \'chicky-chicky-parm-parm.\' Chicken cacciatore? \'Chicky-cacc.\' I call eggs \'pre-birds,\' or \'future birds.\' Root beer is \'super water.\' Tortillas are \'bean blankets.\' And I call forks \'food rakes.',
    'Yeah, I\'ve been a little down. Totally natural. I\'m getting a divorce, but now I\'m ready to pull myself up by some G-strings.',
    'One of my life goals is to be a best man. It\'s a baller position. You get drunk, you make speeches, and you make love to the prettiest bridesmaid. Usually standing from behind.',
    'I\'m like an elephant, OK? If I walk into a room, it\'s like, OK, he\'s in there.',
    'I think you sound like an angel, and everyone else sounds like demons.',
    'Oh, what\'s this in my shoe? Red carpet insole. Everywhere I go, I\'m walking on red carpet.',
    'She broke up with me. Didn\'t really tell me why. Luckily when you\'re the guy, you can just tell people she\'s crazy. \'Hey, Tom, I heard you and Lucy broke up.\' \'Yeah, man. Turns out, she\'s crazy.\' That\'s what they always do on Entourage.',
    'I have no interest in art. Let me clarify — I have no interest in non-nude images.',
    'I have a couple of \'doing caps\' in my wallet. That\'s what I call condoms.',
    'I have never taken the high road, but I tell other people to \'cause then there\'s more room for me on the low road.',
    'No one\'s trying to get with jugglers.',
    'When I bet on horses, I never lose. Why? I bet on all the horses.',
    'I strapped an MP3 player to one of those floor-cleaning robots. Call him DJ Roomba — little guy cruises around and plays music. What\'s hot, DJ Roomba!',
    'Everyone steals. My favorite movie is Love Don\'t Cost a Thing with Nick Cannon. Which is based on Can\'t Buy Me Love, which is based on Kramer vs. Kramer, or something, which I think was Shakespeare.',
    'Modern life. Where are we running? Sometimes what we want is not always where we are… Are we alone? Is the real winter inside our hearts? We are all struggling for definition in a world that resists our increase.',
    'Every now and then, we have these little gatherings, and Leslie gets plastered. One time, I convinced her to try to fax someone a Fruit Roll-Up.',
    'You don\'t know Jay-Z\'s schedule. He\'s a Renaissance man.',
    'Make-A-Baby Tuxedo clothing line. A department store with a guest list. White fur earmuffs for men. Contact lenses that display text messages. Invent a phone that smells good. Own a nightclub, call it Eclipse, that\'s only open for one hour two times a year. Cover charge? Five thousand dollars.'
  ]
}
